# Имя вашего приложения
spring.application.name=shelter
server.port=8082

# Настройки подключения к PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shelter_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Spring сам создаст таблицы в базе на основе наших Java-классов
spring.jpa.hibernate.ddl-auto=update
# Показывать в консоли, какие SQL-запросы делает программа
spring.jpa.show-sql=true
# Диалект для работы именно с Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.web.resources.static-locations=classpath:/static/,file:uploads/
# Максимальный размер одного файла
spring.servlet.multipart.max-file-size=10MB
# Максимальный размер всего запроса (если файлов несколько)
spring.servlet.multipart.max-request-size=10MB

springdoc.packages-to-scan=com.example.shelter.controllers