CREATE TABLE public.users (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255) NOT NULL UNIQUE,
    first_name character varying(255),
    password character varying(255) NOT NULL,
    role character varying(255)
);

CREATE TABLE public.animals (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50),
    species character varying(255),
    gender character varying(255),
    age integer,
    weight double precision,
    description character varying(2000),
    health_status character varying(1000),
    image_url character varying(255),
    status character varying(255)
);

CREATE TABLE public.supplies (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255),
    current_amount double precision,
    target_amount double precision,
    unit character varying(255)
);

CREATE TABLE public.donations (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    amount double precision,
    comment character varying(255),
    donated_at timestamp(6) without time zone,
    user_id bigint,
    CONSTRAINT fkd2p196clbvqgbemy05ndspwu FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE public.volunteer_requests (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    activity_type character varying(255),
    experience character varying(255),
    status character varying(255),
    submitted_at timestamp(6) without time zone,
    user_id bigint,
    CONSTRAINT fkd316mhs5yumrh9i5r4q6wn5c4 FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE public.adoption_requests (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    message character varying(1000),
    request_date timestamp(6) without time zone,
    status character varying(255),
    animal_id bigint,
    user_id bigint,
    CONSTRAINT fkk0y3j8ydm8gr4pfhujbsxi62l FOREIGN KEY (user_id) REFERENCES public.users(id),
    CONSTRAINT fksuopjxcm5287ddo6utappsqil FOREIGN KEY (animal_id) REFERENCES public.animals(id)
);